apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - maasauthpolicy-premium.yaml
  - maasmodelref-simulated-premium.yaml
  - maassubscription-premium.yaml
  - maasauthpolicy-free.yaml
  - maasmodelref-simulated-free.yaml
  - maassubscription-free.yaml
